import type { NextPage } from 'next'
import Head from 'next/head'

import { Box, Heading } from '@chakra-ui/layout';

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading as="h1">HOME PAGE</Heading>
    </Box>
  )
}

export default Home
